//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationDBApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category
    {
        public tbl_category()
        {
            this.tbl_product = new HashSet<tbl_product>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual tbl_category tbl_category1 { get; set; }
        public virtual tbl_category tbl_category2 { get; set; }
        public virtual ICollection<tbl_product> tbl_product { get; set; }
    }
}
